---
<<: !include common/base.yaml

substitutions:
  device_name: basement-ventilation
  device_comment: "ESP32 with 4 relays for basement ventilation"

esphome:
  name: ${device_name}
  comment: ${device_comment}
  on_boot:
    priority: -100
    then:
      - switch.turn_on: mode_low

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

button:
  - <<: !include common/button/restart.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

# Physical relay outputs
switch:
  - platform: gpio
    id: sw_01
    name: "${device_name}_sw_01"
    pin: 15
  - platform: gpio
    id: sw_02
    name: "${device_name}_sw_02"
    pin: 5
  - platform: gpio
    id: sw_03
    name: "${device_name}_sw_03"
    pin: 19
  - platform: gpio
    id: sw_04
    name: "${device_name}_sw_04"
    pin: 23

  # Virtual mode switches
  - platform: template
    id: mode_off
    name: "${device_name}_off"
    turn_on_action:
      - switch.template.publish:
          id: mode_low
          state: OFF
      - switch.template.publish:
          id: mode_mid
          state: OFF
      - switch.template.publish:
          id: mode_high
          state: OFF
      - switch.turn_off: sw_04
      - delay: 0.5s
      - switch.turn_off: sw_03
      - delay: 0.5s
      - switch.turn_off: sw_01
      - delay: 0.5s

  - platform: template
    id: mode_low
    name: "${device_name}_low"
    turn_on_action:
      - switch.template.publish:
          id: mode_off
          state: OFF
      - switch.template.publish:
          id: mode_mid
          state: OFF
      - switch.template.publish:
          id: mode_high
          state: OFF
      - switch.turn_off: sw_04
      - delay: 0.5s
      - switch.turn_off: sw_03
      - delay: 0.5s
      - switch.turn_on: sw_01
      - delay: 0.5s

  - platform: template
    id: mode_mid
    name: "${device_name}_mid"
    turn_on_action:
      - switch.template.publish:
          id: mode_off
          state: OFF
      - switch.template.publish:
          id: mode_low
          state: OFF
      - switch.template.publish:
          id: mode_high
          state: OFF
      - switch.turn_off: sw_04
      - delay: 0.5s
      - switch.turn_on: sw_01
      - delay: 0.5s
      - switch.turn_on: sw_03
      - delay: 0.5s

  - platform: template
    id: mode_high
    name: "${device_name}_high"
    turn_on_action:
      - switch.template.publish:
          id: mode_off
          state: OFF
      - switch.template.publish:
          id: mode_low
          state: OFF
      - switch.template.publish:
          id: mode_mid
          state: OFF
      - switch.turn_on: sw_01
      - delay: 0.5s
      - switch.turn_off: sw_03
      - delay: 0.5s
      - switch.turn_on: sw_04
      - delay: 0.5s
