---
<<: !include common/base.yaml

substitutions:
  device_name: basement-ventilation
  device_comment: "ESP32 with 4 relays for basement ventilation"

esphome:
  name: ${device_name}
  comment: ${device_comment}
  on_boot:
    priority: -100
    then:
      - select.set:
          id: fan_mode
          option: "low"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

button:
  - <<: !include common/button/restart.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

# Physical relay outputs
switch:
  - platform: gpio
    id: sw_01
    name: "${device_name}_sw_01"
    pin: 15
  - platform: gpio
    id: sw_02
    name: "${device_name}_sw_02"
    pin: 5
  - platform: gpio
    id: sw_03
    name: "${device_name}_sw_03"
    pin: 19
  - platform: gpio
    id: sw_04
    name: "${device_name}_sw_04"
    pin: 23

# Fan mode selector
select:
  - platform: template
    id: fan_mode
    name: "${device_name}_mode"
    optimistic: true
    options:
      - "off"
      - "low"
      - "mid"
      - "high"
    set_action:
      - lambda: |-
          if (x == "off") {
            id(sw_04).turn_off();
            delay(500);
            id(sw_03).turn_off();
            delay(500);
            id(sw_01).turn_off();
          } else if (x == "low") {
            id(sw_04).turn_off();
            delay(500);
            id(sw_03).turn_off();
            delay(500);
            id(sw_01).turn_on();
          } else if (x == "mid") {
            id(sw_04).turn_off();
            delay(500);
            id(sw_01).turn_on();
            delay(500);
            id(sw_03).turn_on();
          } else if (x == "high") {
            id(sw_01).turn_on();
            delay(500);
            id(sw_03).turn_off();
            delay(500);
            id(sw_04).turn_on();
          }
