---
<<: !include common/base.yaml

substitutions:
  device_name: basement-ventilation
  device_comment: "ESP32 with 4 relays for basement ventilation"

esphome:
  name: ${device_name}
  comment: ${device_comment}

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

button:
  - <<: !include common/button/restart.yaml

binary_sensor:
  - <<: !include common/binary_sensor/status.yaml

sensor:
  - <<: !include common/sensor/uptime.yaml
  - <<: !include common/sensor/wifi_signal.yaml

text_sensor:
  - <<: !include common/text_sensor/version.yaml
  - <<: !include common/text_sensor/wifi_info.yaml

switch:
  - platform: gpio
    name: "${device_name}_sw_01"
    pin:
      number: 15
  - platform: gpio
    name: "${device_name}_sw_02"
    pin:
      number: 5
  - platform: gpio
    name: "${device_name}_sw_03"
    pin:
      number: 19
  - platform: gpio
    name: "${device_name}_sw_04"
    pin:
      number: 23
