name: Check releases

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-releases:
    uses: x-real-ip/github-actions/.github/workflows/new-release-issue.yaml@main
    strategy:
      matrix:
        include:
          - name: ESP-Home
            type: release
            target: esphome/esphome
            bump: true
            bump_type: containerfile
          - name: Opentherm Gateway
            type: release
            target: Laxilef/OTGateway
    with:
      name: ${{ matrix.name }}
      target: ${{ matrix.target }}
      type: ${{ matrix.type }}
